# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "xbm"
version = "0.1.1"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.74.0"
description = "XBM encoding and decoding library"
documentation = "https://docs.rs/xbm"
readme = "README.md"
repository = "https://github.com/sorairolake/xbm-rs"
license = "Apache-2.0 OR MIT"
keywords = ["encoding", "image", "xbm"]
categories = ["multimedia::encoding", "multimedia::images"]
include = ["/LICENSES", "/README.md", "/src"]

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "png2xbm"
path = "examples/png2xbm.rs"
required-features = ["image"]

[[example]]
name = "xbm2png"
path = "examples/xbm2png.rs"
required-features = ["image"]

[dependencies]
image = { version = "0.25.4", default-features = false, optional = true }
unicode-ident = "1.0.13"

[dev-dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
image = { version = "0.25.4", default-features = false, features = ["png"] }

[features]
default = ["image"]
image = ["dep:image"]
